### ISSUE TITLE
Question: configure processor_host via environment variable

### ISSUE THREAD

**Issue by sweep3092** [keypup-io/cloudtasker#117]
When Cloudtasker use with Rails on Docker Compose, Cloudtasker does not work with setting as below.

```
Cloudtasker.configure do |config|
  config.processor_host = ENV['PROCESSOR_HOST'] # => http://web:3000
end
```

although, with this setting is working.
```
Cloudtasker.configure do |config|
  config.processor_host = 'http://web:3000'
end
```

Can I ask how do I setting `processor_host` via environment variable?

**Comment by alachaum** [comment]
Hey @sweep3092 if the second one works but not the first one, it probably means that your ENV var is not properly set in your Docker container.

You can confirm the issue by doing:
```rb
Cloudtasker.configure do |config|
  puts "ENV['PROCESSOR_HOST']: #{ENV['PROCESSOR_HOST'].inspect}"
  config.processor_host = ENV['PROCESSOR_HOST'] # => http://web:3000
end
```


Maybe this link will help?
https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by sweep3092** [comment]
Thank you @alachaum for the answer.

Of cource, I have confirmed that ENV is applied to the container.

```
cloudtasker-1  | ENV['PROCESSOR_HOST']: "'http://web:3000'"
cloudtasker-1  |
cloudtasker-1  |    ___ _                 _ _            _
cloudtasker-1  |   / __\ | ___  _   _  __| | |_ __ _ ___| | _____ _ __
cloudtasker-1  |  / /  | |/ _ \| | | |/ _` | __/ _` / __| |/ / _ \ '__|
cloudtasker-1  | / /___| | (_) | |_| | (_| | || (_| \__ \   <  __/ |
cloudtasker-1  | \____/|_|\___/ \__,_|\__,_|\__\__,_|___/_|\_\___|_|
cloudtasker-1  |
cloudtasker-1  |
```

but, when I tried to create job, the error has shown below (try to connect http://localhost:3000 as default?):

```
cloudtasker-1  | #<Thread:0x00007fd018a882f8 /usr/local/bundle/gems/cloudtasker-0.13.2/lib/cloudtasker/local_server.rb:72 run> terminated with exception (report_on_exception is true):
cloudtasker-1  | /usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `initialize': Failed to open TCP connection to localhost:3000 (Cannot assign requested address - connect(2) for "localhost" port 3000) (Errno::EADDRNOTAVAIL)
cloudtasker-1  |        from /usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `open'
cloudtasker-1  |        from /usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `block in connect'
cloudtasker-1  |        from /usr/local/bundle/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
cloudtasker-1  |        from /usr/local/bundle/gems/timeout-0.4.1/lib/timeout.rb:193:in `timeout'
cloudtasker-1  |        from /usr/local/lib/ruby/3.2.0/net/http.rb:1269:in `connect'
cloudtasker-1  |        from /usr/local/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
cloudtasker-1  |        from /usr/local/lib/ruby/3.2.0/net/http.rb:1237:in `start'
cloudtasker-1  |        from /usr/local/lib/ruby/3.2.0/net/http.rb:1817:in `request'
cloudtasker-1  |        from /usr/local/bundle/gems/cloudtasker-0.13.2/lib/cloudtasker/backend/redis_task.rb:206:in `deliver'
cloudtasker-1  |        from /usr/local/bundle/gems/cloudtasker-0.13.2/lib/cloudtasker/local_server.rb:87:in `process_task'
cloudtasker-1  |        from /usr/local/bundle/gems/cloudtasker-0.13.2/lib/cloudtasker/local_server.rb:72:in `block in process_jobs'
```

Though, no error has shown with setting processor_host without ENV.
I imagine that the worker threads cannot read ENV or something... what do you think?

**Comment by alachaum** [comment]
The ENV does not really matter once you have set the processor_host.

The URL of tasks is set when jobs are enqueued (in Redis, when working locally).

So the config of jobs are really driven by the main app rather than the local processor.

I suspect that a previous job with localhost:3000 as a target from your earlier tests is still hanging around.

Could you try clearing your Redis instance then retry?

**Comment by sweep3092** [comment]
My apologies, I misunderstood about that who use the config.
I tried to set ENV to mainapp-container, it worked successfully.

Thanks a lot for the detailed answer! It was great help.

**Comment by alachaum** [comment]
No worries, happy to help 😉
