### ISSUE TITLE
ActiveJob Adapter

### ISSUE THREAD

**Issue by vovimayhem** [keypup-io/cloudtasker#12]
It would be cool for Cloudtasker to be a backend for Rails [ActiveJob](https://guides.rubyonrails.org/active_job_basics.html)

This would require implementing an [ActiveJob::QueueAdapter](https://api.rubyonrails.org/v6.0.3.2/classes/ActiveJob/QueueAdapters.html) on this library.

I've already done this for another project, so maybe I can help.

**Comment by retsef** [comment]
It will be very helpfull. If you already did, you can propose with a pull request 😉

**Comment by alachaum** [comment]
@vovimayhem that would be great actually. Would you like to propose a PR? Otherwise I can have a look at that when I've got some spare time.

**Comment by vovimayhem** [comment]
I haven't worked on it yet - I first wanted to know if this feature was on the project's interest or not :)

I think I'll have some time next week, maybe I can take a look at it.

**Comment by vovimayhem** [comment]
I'd say let's ping here if me or anyone starts working on this feature :)

**Comment by alachaum** [comment]
No worries @vovimayhem. No rush :)

**Comment by alachaum** [comment]
Implemented in #18
