### ISSUE TITLE
Speed up the build process on Github

### ISSUE THREAD

**Issue by vovimayhem** [keypup-io/cloudtasker#14]
The build process using Github Actions is cool, but takes a bit of time.

I think I have a couple of ideas to speed it up. Namely:

- Use caching
- Use docker to run the tests

**Comment by vovimayhem** [comment]
Also, given [Codeclimate is free for open source projects](https://codeclimate.com/blog/code-climate-is-free-for-open-source), and that there's a Rubocop plugin for codeclimate, I think we should delegate the code style checks to codeclimate instead, and keep Github Actions focused on running the tests (and even release the gem - I've already done it on other projects)

**Comment by alachaum** [comment]
From memory the part that takes most time is setting up each appraisal context (gems). I haven't had time to investigate caching strategies for that yet.

Codeclimate is a good idea but it's a paying option as cloudtasker is hosted under Keypup's account. If we end up taking a codeclimate subscription I'll switch cloudtasker over.

Let's keep this issue open to track progress on caching gems at build time.

**Comment by vovimayhem** [comment]
> Codeclimate is a good idea but it's a paying option as cloudtasker is hosted under Keypup's account.

It's totally possible to get Codeclimate for free on public repositories, regardless of the repositories' owner account (Keypup in this case). I've done it many ties before for the org I belong to (IcaliaLabs).

**Comment by alachaum** [comment]
Let's see if we can use the native caching capabilities of GitHub actions (I've done it with CircleCI but not with GitHub so far). If it's too constraining then Docker is a good option.

Regarding Codeclimate I'll have a look again. I may have been confused with another service.

**Comment by alachaum** [comment]
Closing this one. Since this issue was raised the build was reworked to 1) separate rubocop and 2) leverage bundler's cache. Build now runs in ~1m.
