### ISSUE TITLE
Long running jobs and HTTP timeout 

### ISSUE THREAD

**Issue by Fodoj** [keypup-io/cloudtasker#23]
More of a question than an issue: how does CloudTasker handle long running jobs? If I would want to run a jog that takes 30 minutes (some video encoding for example), will it timeout? Because I assume by default HTTP request will timeout pretty fast.

**Comment by alachaum** [comment]
So it really depends on two things:
- the caller (Cloud Tasks). The default timeout is 10 mins and can be extended up to 30 mins.
- your runtime (Cloud Run, App Engine, other). For Cloud Run, the default timeout is 5 minutes and can be extended up to 60 minutes.

If the caller (Cloud Tasks) drops, Cloudtasker will keep processing the job until the runtime dies or the thread is cut. But from a caller perspective, the job will be failed and retried.

If you have the opportunity to break down your background jobs in chunks, it's better.

**Comment by Fodoj** [comment]
Cool, so its up to 30 minutes basically. Thanks a lot for the detailed answer!
