### ISSUE TITLE
Ruby 3.0.1 ArgumentError

### ISSUE THREAD

**Issue by shaundowling** [keypup-io/cloudtasker#27]
Hello 

I'm trying to give this gem a whirl on ruby 3.0.1 using rails active job and receive an argument error when enqueuing a job.

```
irb(main):003:0> DummyJob.perform_later("some arg")
E, [2021-04-19T10:10:12.732771 #87494] ERROR -- : Failed enqueuing DummyJob to Cloudtasker(default): ArgumentError (wrong number of arguments (given 1, expected 0))
/XXX/vendor/cache/ruby/3.0.0/gems/cloudtasker-0.11.0/lib/cloudtasker/worker.rb:209:in `schedule_time': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

I think it is related to the positional arguments changes [detailed here](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

I checked out the source and can confirm tests are green on 2.7.3 and red on 3.0.1

Is there any plan for 3.x support? I'm happy to pitch in to find a solution i'm just not sure where to start.

**Comment by alachaum** [comment]
@shaundowling thanks for reporting. I'll have a look at this and fix it. It should take long to make cloudtasker 3.0-compatible.

**Comment by shaundowling** [comment]
@alachaum np, thanks for the quick reply. It looked like it might be tricky depending on what backwards compatibility is required.

This lib seems like the only serious game in town for running ruby on GCP so appreciate you guys open sourcing it 🙌

**Comment by alachaum** [comment]
Hehe no worries. 

By the way, don't hesitate to checkout its little brother for Pub/Sub: https://github.com/keypup-io/cloudenvoy Any feedback appreciated there as well! (though we might have Rb3 compatibility issues on this project as well)

**Comment by shaundowling** [comment]
cheers will take a look at that, currently looking into this as an activejob backend replacement for delayed job as the old pull worker approach doesn't really fit anymore.

I'll roll back to 2.x and give it a try.

**Comment by alachaum** [comment]
@shaundowling feel free to play around with my branch on #32. The branch has `v0.12.rc10` + Ruby 3 support.

I'm targeting `v0.13` to officially release Ruby 3 support.

**Comment by alachaum** [comment]
Release candidate `v0.13.rc1` with support for Ruby 3 has been pushed to rubygems.
