### ISSUE TITLE
[Local dev server] Workers/jobs work only sometimes, throwing `NoMethodError` for the `deliver` method when failing

### ISSUE THREAD

**Issue by feute** [keypup-io/cloudtasker#29]
Hello! I've been trying out this library for a few hours and so far it's being inconsistent. I've been testing with the `DummyWorker` and `ExampleJob` classes and they work *sometimes*. What I mean by that is that sometimes the worker works while the job doesn't, and viceversa. I tried starting the server, `cloudtasker`, and console in various ways: using separate terminals, using a Procfile with `foreman`; I've tried executing them using `bundle exec`, calling the worker/job differently (using `perform_async` and `perform_in` in the case of the worker, with and without an argument.) Sometimes the worker doesn't work, but I stop and start everything again and it works, but the job doesn't. I can't get them to work properly. 

If either of them is working, it keeps working for the rest of the server/console session (or at least for a while.)

The error that I'm getting from the `cloudtasker` logs is:

```
#<Thread:0x000055d665c8ebf0 /home/angel/.rvm/gems/ruby-2.7.0/gems/cloudtasker-0.11.0/lib/cloudtasker/local_server.rb:72 run> terminated with exception (report_on_exception is true):
/home/angel/.rvm/gems/ruby-2.7.0/gems/cloudtasker-0.11.0/lib/cloudtasker/local_server.rb:87:in `process_task': undefined method `deliver' for nil:NilClass (NoMethodError)
    from /home/angel/.rvm/gems/ruby-2.7.0/gems/cloudtasker-0.11.0/lib/cloudtasker/local_server.rb:72:in `block in process_jobs'
```

From what I understand, I guess that [`process_task`](https://github.com/keypup-io/cloudtasker/blob/master/lib/cloudtasker/local_server.rb#L81) callers are not setting the `task` parameter to the proper value in all cases, such as in [`process_jobs`](https://github.com/keypup-io/cloudtasker/blob/master/lib/cloudtasker/local_server.rb#L62).

Some info about the environment:
- Ruby 2.7.0
- Rails 6.1.0
- cloudtasker 0.11

I have redis installed (along with the `redis` gem.) The initializer is the simplest one, with only a `config.processor_host` line inside the config block.

**Comment by alachaum** [comment]
Hi @feute,

It's weird, it's as if the local server queue was filled with an empty task. Would you be able to try using `v0.12.rc9` instead and let me know if the result is the same on your side?

Also, side question, do you have any logic in your application regularly clearing the cache? Or any other application running in parallel tampering with the cache?

If so, you may point Cloudtasker to a different redis database using the `config.redis = { url: 'redis://localhost:6379/5' }` configuration option.

**Comment by feute** [comment]
I only use redis for ActionCable. I tried adding the config line for redis to use the `/5` database but it didn't do anything, I guess it's because the default is `/0` while ActionCable is configured to use `/1`, so it doesn't interfere.

I installed `v0.12.rc9` and it seemed to work better. Sometimes I get the error with the `DummyWorker`: I fire up the console and call `perform_async` on the class and I get the error most of the time, but after retrying once or twice it starts to work. I kept the `config.redis` line just in case.

Is it safe to use `v0.12.rc9` on production? I only mean to use it as a backend for ActiveJob (at least for now).

**Comment by feute** [comment]
That's what I thought, that it could be affecting the local server only. I think I'm going to use `v0.12.rc9` because it works better for me.

I do have only one cloudtasker process running. I start it with `foreman start`, with no extra configuration.

Anyway, if I find out the cause of this particular error I'll update this issue. For now, I'll use the `0.12.rc9` version.

Thank you!

**Comment by alachaum** [comment]
I'll still commit a small patch to avoid these errors on `v0.12`. Having some guarding against nil on the local server won't hurt.

Thanks for reporting this!
