### ISSUE TITLE
Odd error on boot

### ISSUE THREAD

**Issue by matthewford** [keypup-io/cloudtasker#37]
After sorting redis to store the cron jobs, now im now seeing an odd error on boot:

`ogle::Gax::PermissionDeniedError: GaxError RPC failed, caused by 7:Permission denied on 'locations/eu-west2' (or it may not exist).. debug_error_string:{"created":"@1627941649.186614634","description":"Error received from peer ipv4:142.250.200.10:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Permission denied on 'locations/eu-west2' (or it may not exist).","grpc_status":7}`

It used to boot - do you think its just a GCP error? Could permissions be missing after this used to boot?

**Comment by matthewford** [comment]
Seems to occur when trying to create the schedule on boot.

**Comment by matthewford** [comment]
no I replaced the permission rather when I was trying to add a new permission in :facepalm:

**Comment by alachaum** [comment]
No worries @matthewford 😃 

I was about to reply but glad you found the root cause!
