### ISSUE TITLE
TypeError: wrong argument type Symbol (expected String)

### ISSUE THREAD

**Issue by eLod** [keypup-io/cloudtasker#39]
Rails 5.2.2, gem version 0.11.

It seems the `google.cloud.tasks.v2beta3.HttpRequest` message has a `map :headers, :string, :string, 3` (google-cloud-tasks 1.1.3, lib/google/cloud/tasks/v2beta3/target_pb.rb), however `Cloudtasker::Backend::GoogleCloudTask.format_task_payload` does a json encode-decode (deep duplication judging by the comment) with `symbolize_names: true`, which makes `payload[::http_request][:headers]` have symbol keys, which in turn raises an error in google-gax (in title). (Furthermore the method would overwrite `Content-Type` but it sets the key as a string, while `Cloudtasker::WorkerHandler#task_payload` already set it but json encode-decode converted it to a symbol key.)

My quick fix is prepend a module and stringify the keys in the headers (eg in the cloudtasker initializer)

```ruby
module CloudTaskerFix
  def format_task_payload(payload)
    super.tap { |pld| pld.dig(:http_request, :headers)&.stringify_keys! }
  end
end

require 'cloudtasker/backend/google_cloud_task'
Cloudtasker::Backend::GoogleCloudTask.singleton_class.prepend CloudTaskerFix
```

**Comment by alachaum** [comment]
I'll do some tests on my end. I don't recall having these kind of issues. On the other side `google-cloud-tasks` `v1.1.3` is fairly old (October 2019) so it's possible they didn't add support for symbol keys.

I'll do some testing on my end and let you know.

**Comment by eLod** [comment]
well `google-cloud-tasks` is pinned at `~>1.0` (even for the rc variants), i checked `v.1.5.1` and the target_pb still contains the `map :headers, :string, :string, 3` line, so i haven't checked upgrading `google-cloud-tasks`

**Comment by alachaum** [comment]
It might actually be related to google-protobuff. I'll do more testing

**Comment by eLod** [comment]
well, this is a legacy application, but i found that actually `google-protobuf` was pinned to an old version (3.7.0-rc2), once resolved i could update `google-cloud-tasks` to 1.5.1 (and other libs like `google-gax` and `googleapis-common-protos`) and the issue is resolved. most likely the upgrade of those google libs solved the problem. feel free to close the issue.

**Comment by eLod** [comment]
for reference the old-new versions:

```
-    google-cloud-tasks (1.1.3)
-      google-gax (~> 1.7)
+    google-cloud-tasks (1.5.1)
+      google-gax (~> 1.8)
       googleapis-common-protos (>= 1.3.9, < 2.0)
+      googleapis-common-protos-types (>= 1.0.4, < 2.0)
       grpc-google-iam-v1 (~> 0.6.9)
-    google-gax (1.7.1)
-      google-protobuf (~> 3.2)
-      googleapis-common-protos (>= 1.3.5, < 2.0)
-      googleauth (>= 0.6.2, < 0.10.0)
-      grpc (>= 1.7.2, < 2.0)
+    google-gax (1.8.1)
+      google-protobuf (~> 3.9)
+      googleapis-common-protos (>= 1.3.9, < 2.0)
+      googleauth (~> 0.9)
+      grpc (~> 1.24)
       rly (~> 0.2.3)
-    google-protobuf (3.7.1)
-    googleapis-common-protos (1.3.9)
-      google-protobuf (~> 3.0)
-      googleapis-common-protos-types (~> 1.0)
-      grpc (~> 1.0)
-    googleapis-common-protos-types (1.0.4)
-      google-protobuf (~> 3.0)
-    googleauth (0.8.1)
+    google-protobuf (3.17.3)
+    googleapis-common-protos (1.3.11)
+      google-protobuf (~> 3.14)
+      googleapis-common-protos-types (>= 1.0.6, < 2.0)
+      grpc (~> 1.27)
+    googleapis-common-protos-types (1.1.0)
+      google-protobuf (~> 3.14)
+    googleauth (0.9.0)
-    grpc (1.18.0)
-      google-protobuf (~> 3.1)
-      googleapis-common-protos-types (~> 1.0.0)
-    grpc-google-iam-v1 (0.6.9)
-      googleapis-common-protos (>= 1.3.1, < 2.0)
-      grpc (~> 1.0)
+    grpc (1.38.0)
+      google-protobuf (~> 3.15)
+      googleapis-common-protos-types (~> 1.0)
+    grpc-google-iam-v1 (0.6.11)
+      google-protobuf (~> 3.14)
+      googleapis-common-protos (>= 1.3.11, < 2.0)
+      grpc (~> 1.27)
```

**Comment by alachaum** [comment]
Going to close this one. The solution is `bundle update google-protobuf`
