### ISSUE TITLE
Cloudtasker::Cron::Schedule trying to access wrong project and queue - not respecting initializer configuration

### ISSUE THREAD

**Issue by wagnerpereira** [keypup-io/cloudtasker#57]
Hey @alachaum, any idea why should the app starts to get the wrong project id ?

It's seems google SDK it getting the project ID from the application default user on the environment and not from the cloudtasker initializer configuration.

The documentations says that the configuration and project id on methods has precedency:
https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigquery/AUTHENTICATION.md#project-and-credential-lookup.

This erro started after migration from long-lived json keys to short-lived workload identity federation. But I guess that any error that I may have made in the service accounts should not take precedence and the hard coded project id that I am passing to cloudtasker and then to cloud SDK and Cloud Task lib.

### Example of the error on instance deploy, cloudtasker load, that avoids app to start.
<img width="1504" alt="Screen Shot 2022-03-22 at 21 47 34" src="https://user-images.githubusercontent.com/2737595/159714862-fa9e2c88-aba9-45ea-bace-26517fcdb215.png">

**Comment by alachaum** [comment]
The `gcp_project_id` in Cloudtasker is only used to build the URIs of the queues (= location of the queues), not to configure the Google Cloud SDK. The Google Cloud SDK should always be configured from "environment" (= run user).

From what I see here, the `gcp_project_id` is set to `fabrica-dev` in Cloudtasker. Now it seems your Cloud Run `run user` doesn't have permission to access the the Google Task queues in `fabrica-dev`. It's essentially a matter of IAM permission.

From memory you should go into `fabrica-dev > IAM` then allow your `staging > cloud run account` to read/update the queues (see [this section](https://github.com/keypup-io/cloudtasker#cloud-tasks-authentication--permissions) for the required permissions)

Does that make sense or am I missing the issue?

**Comment by alachaum** [comment]
Oh right I see now :) Yes, this kind of issues can also happen locally when running multiple apps with the same redis db.

Glad you found the issue! By the way, I still have the plan to integrate GCP Scheduler to Cloudtasker. It's just been a bit busy on my side recently.

**Comment by wagnerpereira** [comment]
Thank you @alachaum , I tried to alocate a dev last year to help with this schedule feature. We are having some issues with schedule tasks being lost / no rescheduled.

I will keep trying to find a space in out products agenda to help this importante project, mostly with this schedule jobs  resource.

Thank you again.
