### ISSUE TITLE
Make Queue Prefix not necessary

### ISSUE THREAD

**Issue by schanjr** [keypup-io/cloudtasker#77]
From readme.md, seems the guideline is to create a queue prefix based on App name like `my-app-default`. 

This makes a very big assumption about naming things in the GCP platform. Queues are also project specific, so I don't quite see the need to force clients to specify prefix via `CLOUDTASKER_GCP_QUEUE_PREFIX` 

What ends up happening when a queue is used by the some monolithic app that handles multiple jobs: 
`my-app-default`
`my-app-sms-notify-update`
`my-app-sms-notify-delete`
`my-app-email-send-campaign`

I would prefer to name the queues as:
`sms-notify-update`
`sms-notify-delete`
`email-send-campaign`

So it is less cluttered and I can interpret with an actual meaningful prefix (but not enforced by some way by cloud tasker client) 
- sms-<|some-job-action|> -> deals with sms jobs
- email-<|some-job-action|>* -> deals with emails jobs

**Comment by alachaum** [comment]
Hi @schanjr , sure feel free to submit a PR to make the prefix optional. Just search for `gcp_queue_prefix` then handle the case where it's `nil`.

Cloudtasker was primarily designed for applications running on Cloud Run (pseudo-serverless), which rather tend to be micro-service oriented. Hence the approach to prefix queues so they are properly organised in Cloud Tasks.
